# Generated by Django 5.1.1 on 2024-09-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_vinylrecord_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinylrecord',
            name='image',
            field=models.ImageField(default='static\\images\tyler.jpg', upload_to='images/'),
        ),
    ]
