# Generated by Django 5.1.1 on 2024-09-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_vinylrecord_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinylrecord',
            name='image',
            field=models.ImageField(default='images/3b921c51dc99d9fb2be192af3ec14f72.jpg', upload_to='images/'),
        ),
    ]
