# Generated by Django 5.1.1 on 2024-09-14 06:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_vinylrecord_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinylrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
