# Generated by Django 5.1.1 on 2024-09-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_vinylrecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinylrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
