# Generated by Django 5.1.1 on 2024-09-16 10:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_vinylrecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinylrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
