# Generated by Django 5.1.1 on 2024-09-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_vinylrecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinylrecord',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
