# Generated by Django 5.1.1 on 2024-09-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_vinylrecord_image'),
        ('main', '0008_vinylrecord_user'),
    ]

    operations = [
    ]
