# Generated by Django 5.1.1 on 2024-09-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge_20240921_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinylrecord',
            name='genre',
            field=models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('hiphop', 'Hip Hop'), ('indie', 'Indie'), ('electronic', 'Electronic'), ('country', 'Country'), ('rhythm_and_blues', 'Rhythm and Blues'), ('other', 'Other')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
