# Generated by Django 5.1.1 on 2024-09-29 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_vinylrecord_genre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vinylrecord',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_vinyls', to=settings.AUTH_USER_MODEL),
        ),
    ]
