# Generated by Django 5.1.1 on 2024-10-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_vinylrecord_favorited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinylrecord',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
