# Generated by Django 5.1.1 on 2024-10-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_vinylrecord_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinylrecord',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
