# Generated by Django 5.1.1 on 2024-11-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_vinylrecord_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinylrecord',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
